-- Initial schema for Team Handoff Notes.
-- D1 (SQLite). IDs are UUID text generated by the Worker.
-- Booleans are stored as INTEGER 0/1. Timestamps are ISO-8601 UTC text.

PRAGMA foreign_keys = ON;

-- ---------------------------------------------------------------------------
-- users: identities created on first successful Google login.
-- ---------------------------------------------------------------------------
CREATE TABLE users (
  id TEXT PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  avatar_url TEXT,
  role TEXT NOT NULL CHECK (role IN ('admin', 'editor', 'viewer')) DEFAULT 'viewer',
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

-- ---------------------------------------------------------------------------
-- teams: a workspace tied to one Google Drive shared folder.
-- ---------------------------------------------------------------------------
CREATE TABLE teams (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  drive_folder_id TEXT,
  drive_shared_drive_id TEXT,
  drive_inbox_page_id TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

-- ---------------------------------------------------------------------------
-- team_members: per-team role. A user's effective role for a team's data.
-- ---------------------------------------------------------------------------
CREATE TABLE team_members (
  id TEXT PRIMARY KEY,
  team_id TEXT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK (role IN ('admin', 'editor', 'viewer')) DEFAULT 'viewer',
  invited_by TEXT REFERENCES users(id),
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  UNIQUE (team_id, user_id)
);
CREATE INDEX idx_team_members_user ON team_members(user_id);

-- ---------------------------------------------------------------------------
-- sessions: server-side session store backing the HttpOnly session cookie.
-- ---------------------------------------------------------------------------
CREATE TABLE sessions (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX idx_sessions_user ON sessions(user_id);
CREATE INDEX idx_sessions_expires ON sessions(expires_at);

-- ---------------------------------------------------------------------------
-- pages: hierarchical page metadata (title, status, assignee, ordering).
-- ---------------------------------------------------------------------------
CREATE TABLE pages (
  id TEXT PRIMARY KEY,
  team_id TEXT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  parent_id TEXT REFERENCES pages(id) ON DELETE CASCADE,
  title TEXT NOT NULL DEFAULT '제목 없음',
  status TEXT NOT NULL CHECK (status IN ('in_progress', 'handoff_pending', 'done', 'on_hold')) DEFAULT 'in_progress',
  assignee_id TEXT REFERENCES users(id),
  due_date TEXT,
  tags TEXT NOT NULL DEFAULT '[]', -- JSON array of strings
  order_key REAL NOT NULL DEFAULT 0,
  version INTEGER NOT NULL DEFAULT 1,
  is_system INTEGER NOT NULL DEFAULT 0, -- e.g. the "Drive 가져오기함" inbox page
  is_deleted INTEGER NOT NULL DEFAULT 0,
  deleted_at TEXT,
  created_by TEXT NOT NULL REFERENCES users(id),
  updated_by TEXT NOT NULL REFERENCES users(id),
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX idx_pages_team ON pages(team_id, is_deleted);
CREATE INDEX idx_pages_parent ON pages(parent_id);
CREATE INDEX idx_pages_assignee ON pages(assignee_id);
CREATE INDEX idx_pages_status ON pages(team_id, status);

-- ---------------------------------------------------------------------------
-- page_contents: page body, stored separately from metadata since it
-- changes far more often (autosave). One row per page.
-- ---------------------------------------------------------------------------
CREATE TABLE page_contents (
  page_id TEXT PRIMARY KEY REFERENCES pages(id) ON DELETE CASCADE,
  content_json TEXT NOT NULL DEFAULT '{"blocks":[]}',
  version INTEGER NOT NULL DEFAULT 1,
  updated_by TEXT NOT NULL REFERENCES users(id),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

-- ---------------------------------------------------------------------------
-- attachments: metadata only. Real file bytes live in Google Drive
-- (optionally mirrored to R2). Never store file bytes in D1.
-- ---------------------------------------------------------------------------
CREATE TABLE attachments (
  id TEXT PRIMARY KEY,
  page_id TEXT NOT NULL REFERENCES pages(id) ON DELETE CASCADE,
  file_name TEXT NOT NULL,
  extension TEXT NOT NULL,
  mime_type TEXT NOT NULL,
  size_bytes INTEGER NOT NULL,
  checksum TEXT,
  status TEXT NOT NULL CHECK (status IN ('pending', 'ready', 'failed')) DEFAULT 'pending',
  drive_file_id TEXT,
  drive_web_view_link TEXT,
  r2_backup_key TEXT,
  idempotency_key TEXT,
  failure_reason TEXT,
  is_deleted INTEGER NOT NULL DEFAULT 0,
  deleted_at TEXT,
  uploaded_by TEXT NOT NULL REFERENCES users(id),
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX idx_attachments_page ON attachments(page_id, is_deleted);
CREATE UNIQUE INDEX idx_attachments_drive_file ON attachments(drive_file_id) WHERE drive_file_id IS NOT NULL;
CREATE UNIQUE INDEX idx_attachments_idempotency ON attachments(idempotency_key) WHERE idempotency_key IS NOT NULL;

-- ---------------------------------------------------------------------------
-- comments
-- ---------------------------------------------------------------------------
CREATE TABLE comments (
  id TEXT PRIMARY KEY,
  page_id TEXT NOT NULL REFERENCES pages(id) ON DELETE CASCADE,
  author_id TEXT NOT NULL REFERENCES users(id),
  body TEXT NOT NULL,
  is_deleted INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX idx_comments_page ON comments(page_id, is_deleted);

-- ---------------------------------------------------------------------------
-- handoff_status_history
-- ---------------------------------------------------------------------------
CREATE TABLE handoff_status_history (
  id TEXT PRIMARY KEY,
  page_id TEXT NOT NULL REFERENCES pages(id) ON DELETE CASCADE,
  from_status TEXT,
  to_status TEXT NOT NULL,
  changed_by TEXT NOT NULL REFERENCES users(id),
  changed_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX idx_status_history_page ON handoff_status_history(page_id, changed_at);

-- ---------------------------------------------------------------------------
-- activity_logs: generic audit trail (page edits, attachment events, etc).
-- ---------------------------------------------------------------------------
CREATE TABLE activity_logs (
  id TEXT PRIMARY KEY,
  team_id TEXT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  page_id TEXT REFERENCES pages(id) ON DELETE CASCADE,
  actor_id TEXT REFERENCES users(id),
  action TEXT NOT NULL,
  metadata_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX idx_activity_team ON activity_logs(team_id, created_at);
CREATE INDEX idx_activity_page ON activity_logs(page_id, created_at);

-- ---------------------------------------------------------------------------
-- drive_sync_state: one row per team, tracks incremental sync cursor.
-- ---------------------------------------------------------------------------
CREATE TABLE drive_sync_state (
  team_id TEXT PRIMARY KEY REFERENCES teams(id) ON DELETE CASCADE,
  last_synced_at TEXT,
  last_page_token TEXT,
  status TEXT NOT NULL CHECK (status IN ('idle', 'running', 'failed')) DEFAULT 'idle',
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

-- ---------------------------------------------------------------------------
-- drive_sync_logs: history of each sync run for observability/debugging.
-- ---------------------------------------------------------------------------
CREATE TABLE drive_sync_logs (
  id TEXT PRIMARY KEY,
  team_id TEXT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  trigger TEXT NOT NULL CHECK (trigger IN ('manual', 'cron')) DEFAULT 'manual',
  status TEXT NOT NULL CHECK (status IN ('success', 'failed', 'partial')) DEFAULT 'success',
  files_added INTEGER NOT NULL DEFAULT 0,
  files_updated INTEGER NOT NULL DEFAULT 0,
  files_skipped INTEGER NOT NULL DEFAULT 0,
  error_message TEXT,
  started_at TEXT NOT NULL,
  finished_at TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
CREATE INDEX idx_drive_sync_logs_team ON drive_sync_logs(team_id, started_at);
